order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8081
  grpc-addr: 127.0.0.1:5001

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8082
  grpc-addr: 127.0.0.1:5002
